### ISSUE TITLE
QXcbConnection: XCB error

### ISSUE THREAD

**Issue by alakran** [kirigayakazushin/deepin-topbar#12]
Hi, awesome bar. Thanks for that :)

When I started in a terminal this text show:
QXcbConnection: XCB error: 5 (BadAtom), sequence: 545, resource id: 1818886716, major code: 18 (ChangeProperty), minor code: 0

After that, all de plugins load ok.
![deepinscreenshot_select-area_20170826080435](https://user-images.githubusercontent.com/163556/29741575-720f52e2-8a35-11e7-99c3-ec8a29e9e6c9.png)
![deepinscreenshot_select-area_20170826080456](https://user-images.githubusercontent.com/163556/29741576-7214a53a-8a35-11e7-9fce-ed6faacf8948.png)

ArchLinux + Deepin DE

**Comment by kirigayakazushin** [comment]
Thinks for the feekback!  I'll check it out.
