### ISSUE TITLE
编译出错了

### ISSUE THREAD

**Issue by ktlsl** [kirigayakazushin/deepin-topbar#13]
执行make出现:cd frame/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/lsl/Desktop/deepin-topbar/frame/frame.pro -o Makefile ) && make -f Makefile 
Project ERROR: xcb-util development package not found
Makefile:43: recipe for target 'sub-frame-make_first' failed
make: *** [sub-frame-make_first] Error 3

**Comment by kirigayakazushin** [comment]
编译依赖在dev分支的readme上。  安装libxcb-util-dev
