### ISSUE TITLE
cpu占用有点高,笔记本风扇在狂飙

### ISSUE THREAD

**Issue by ktlsl** [kirigayakazushin/deepin-topbar#14]
希望能够优化下,这个topbar很不错

**Comment by kirigayakazushin** [comment]
编译的是master分支还是dev分支？

尝试逐步删除/usr/lib/deepin-topbar/plugins里面的插件，删除一个就重启一次deepin-topbar，如果删除哪个插件以后没有再出现cpu占用过高，拜托反馈一下。 我个人觉得可能是/usr/lib/deepin-topbar/plugins/libsysteminfo.so

**Comment by ktlsl** [comment]
使用的是安装版的,尝试下删除,程序直接不能运行了
