### ISSUE TITLE
设置界面出现错位,点击后错位更严重

### ISSUE THREAD

**Issue by ktlsl** [kirigayakazushin/deepin-topbar#16]
![deepinscreenshot_select-area_20170830220339](https://user-images.githubusercontent.com/11488902/29876615-ea384aa6-8dcf-11e7-8b6a-e71cad0ef931.png)
![deepinscreenshot_select-area_20170830220339](https://user-images.githubusercontent.com/11488902/29876609-e3a4109e-8dcf-11e7-8de2-5b164f3a8d14.png)

**Comment by kirigayakazushin** [comment]
这个界面还是最初的测试页面，还没有写新的。
