### ISSUE TITLE
请问下，编译后怎么安装，按照wiki里面的编译安装后启动会闪退

### ISSUE THREAD

**Issue by ktlsl** [kirigayakazushin/deepin-topbar#17]

**Comment by kirigayakazushin** [comment]
在终端运行deepin-topbar，然后等待闪退以后，把日志上传上来吧。

**Comment by ktlsl** [comment]
![deepinscreenshot_select-area_20170908220731](https://user-images.githubusercontent.com/11488902/30215333-430d43b6-94e2-11e7-853d-6a72eb834204.png)

**Comment by kirigayakazushin** [comment]
@ktlsl  不然，，你还是装我ppa里面的吧。。试试吧。
