### ISSUE TITLE
Make a deb package for deepin-topbbar

### ISSUE THREAD

**Issue by altntowin** [kirigayakazushin/deepin-topbar#19]
hi i like your application
but i don't how to install it, i don't know how to compile it,
so i have a sugguestion for you, could you make a deb package for deepin-topbar?
is going to be more easier to install :+1: :)

**Comment by swarupsro** [comment]
already has a deb file!

**Comment by altntowin** [comment]
where is it?

**Comment by swarupsro** [comment]
[Deepin Plugins](https://github.com/swarupsro/Deepin-Deb/tree/master/Plugins/u3)

**Comment by kirigayakazushin** [comment]
@altntowin  see https://blog.mkacg.com/2017/07/20/topbar-PPA/

@swarupsro  so sorry, my mistake. version number is error. I've fixed the bug and updated the new version.
