### ISSUE TITLE
Left icon not show in dde 15.5 Beta

### ISSUE THREAD

**Issue by emhaye** [kirigayakazushin/deepin-topbar#26]
![left-icon](https://user-images.githubusercontent.com/1796162/32990300-c336ee34-cd59-11e7-8840-c7ac3f131936.png)

**Comment by emhaye** [comment]
Update:
in console log
```
QXcbConnection: XCB error: 10 (BadAccess), sequence: 783, resource id: 73400367, major code: 142 (Unknown), minor code: 1                    
QXcbConnection: XCB error: 10 (BadAccess), sequence: 863, resource id: 111149066, major code: 142 (Unknown), minor code: 1
```

**Comment by emhaye** [comment]
Sorry, icon dde not found

**Comment by kirigayakazushin** [comment]
@emhaye  https://github.com/kirigayakazushin/deepin-topbar/commit/53260652f0c0a356c4c065e3eaa74f8a2726cc26  added.

**Comment by emhaye** [comment]
@kirigayakazushin thank you

**Comment by emhaye** [comment]
@kirigayakazushin any idea to set bold app name?
