### ISSUE TITLE
fatal error: DWindowManagerHelper: No such file or directory

### ISSUE THREAD

**Issue by ray6an1** [kirigayakazushin/deepin-topbar#4]
When i am trying to build the package, it shows the error:

raihan@lenovo:~/deepin-topbar/build$ make
cd frame/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/raihan/deepin-topbar/frame/frame.pro -o Makefile ) && make -f Makefile 
make[1]: Entering directory '/home/raihan/deepin-topbar/build/frame'
g++ -c -m64 -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DQT_MESSAGELOGCONTEXT -DQT_MESSAGELOGCONTEXT -DQT_NO_DEBUG -DQT_X11EXTRAS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I../../frame -I. -I../../interfaces -I../../widgets -isystem /usr/include/libdtk-1.0/DWidget -isystem /usr/include/libdtk-1.0/DBase -isystem /usr/include/libdtk-1.0/DUtil -isystem /usr/include/libdframeworkdbus-1.0 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o switchitem.o ../../widgets/switchitem.cpp
g++ -c -m64 -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DQT_MESSAGELOGCONTEXT -DQT_MESSAGELOGCONTEXT -DQT_NO_DEBUG -DQT_X11EXTRAS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I../../frame -I. -I../../interfaces -I../../widgets -isystem /usr/include/libdtk-1.0/DWidget -isystem /usr/include/libdtk-1.0/DBase -isystem /usr/include/libdtk-1.0/DUtil -isystem /usr/include/libdframeworkdbus-1.0 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o main.o ../../frame/main.cpp
g++ -c -m64 -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DQT_MESSAGELOGCONTEXT -DQT_MESSAGELOGCONTEXT -DQT_NO_DEBUG -DQT_X11EXTRAS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I../../frame -I. -I../../interfaces -I../../widgets -isystem /usr/include/libdtk-1.0/DWidget -isystem /usr/include/libdtk-1.0/DBase -isystem /usr/include/libdtk-1.0/DUtil -isystem /usr/include/libdframeworkdbus-1.0 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o mainframe.o ../../frame/mainframe.cpp
In file included from ../../frame/item/item.h:4:0,
                 from ../../frame/item/pluginsitem.h:5,
                 from ../../frame/controller/pluginscontroller.h:5,
                 from ../../frame/controller/pluginsitemcontroller.h:4,
                 from ../../frame/mainpanel.h:4,
                 from ../../frame/mainframe.cpp:2:
../../frame/utils/itempopupwindow.h:7:32: fatal error: DWindowManagerHelper: No such file or directory
 #include <DWindowManagerHelper>
                                ^
compilation terminated.
Makefile:494: recipe for target 'mainframe.o' failed
make[1]: *** [mainframe.o] Error 1
make[1]: Leaving directory '/home/raihan/deepin-topbar/build/frame'
Makefile:43: recipe for target 'sub-frame-make_first' failed
make: *** [sub-frame-make_first] Error 2

**Comment by kirigayakazushin** [comment]
you need to build an install latest code. https://github.com/linuxdeepin/deepin-tool-kit

**Comment by renorram** [comment]
After some struggling installing deepin-tool-kit, I tried againt to install and i got some undefined reference errors:
```
cd frame/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/xxxxx/deepin-topbar/frame/frame.pro -o Makefile ) && make -f Makefile 
make[1]: Entering directory '/home/xxxxx/deepin-topbar/build/frame'
g++ -m64 -Wl,-O1 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu -o ../../../deepin-topbar/dde-topbar switchitem.o main.o mainframe.o pluginloader.o pluginscontroller.o pluginsitem.o pluginsitemcontroller.o mainpanel.o frame.o item.o stretchitem.o frameshadow.o itempopupwindow.o moc_switchitem.o moc_mainframe.o moc_pluginloader.o moc_pluginscontroller.o moc_pluginsitem.o moc_pluginsitemcontroller.o moc_mainpanel.o moc_frame.o moc_item.o moc_stretchitem.o moc_frameshadow.o moc_itempopupwindow.o   -L/usr/X11R6/lib64 -lxcb-ewmh -lxcb -ldtkwidget -ldtkbase -ldtkutil -ldframeworkdbus -lX11 -lQt5X11Extras -lQt5Widgets -lQt5Gui -lQt5DBus -lQt5Core -lGL -lpthread 
mainframe.o: In function `MainFrame::init()':
mainframe.cpp:(.text+0x3b5): undefined reference to `Dtk::Widget::DBlurEffectWidget::setMaskColor(Dtk::Widget::DBlurEffectWidget::MaskColorType)'
mainframe.o: In function `MainFrame::registerDesktop()':
mainframe.cpp:(.text+0xbcd): undefined reference to `Dtk::Widget::DForeignWindow::fromWinId(unsigned long long)'
mainframe.cpp:(.text+0xbdd): undefined reference to `Dtk::Widget::DForeignWindow::wmClass() const'
itempopupwindow.o: In function `ItemPopupWindow::compositeChanged()':
itempopupwindow.cpp:(.text+0x60): undefined reference to `Dtk::Widget::DWindowManagerHelper::hasComposite() const'
itempopupwindow.o: In function `ItemPopupWindow::ItemPopupWindow(QWidget*)':
itempopupwindow.cpp:(.text+0xb57): undefined reference to `Dtk::Widget::DWindowManagerHelper::instance()'
itempopupwindow.cpp:(.text+0xb70): undefined reference to `Dtk::Widget::DArrowRectangle::setBackgroundColor(Dtk::Widget::DBlurEffectWidget::MaskColorType)'
itempopupwindow.cpp:(.text+0xb93): undefined reference to `Dtk::Widget::DWindowManagerHelper::hasCompositeChanged()'
itempopupwindow.cpp:(.text+0xc02): undefined reference to `Dtk::Widget::DWindowManagerHelper::staticMetaObject'
collect2: error: ld returned 1 exit status
Makefile:201: recipe for target '../../../deepin-topbar/dde-topbar' failed
make[1]: *** [../../../deepin-topbar/dde-topbar] Error 1
make[1]: Leaving directory '/home/xxxxx/deepin-topbar/build/frame'
Makefile:43: recipe for target 'sub-frame-make_first' failed
make: *** [sub-frame-make_first] Error 2
```
I tried to see if was missing libdtk but is normal:
```libdtkwidget is already the newest version (0.2.9-1+b1).```

**Comment by renorram** [comment]
It worked after update for 15.4.1.

**Comment by kirigayakazushin** [comment]
@ray6an1  https://blog.mkacg.com/2017/07/20/topbar-PPA/ please use it.
