### ISSUE TITLE
Black border bottom

### ISSUE THREAD

**Issue by rafipriatna** [kirigayakazushin/deepin-topbar#44]
Hi,
I really love your works, but i want ask something..
How to delete this black border bottom?
![deepinscreenshot_select-area_20180313192857](https://user-images.githubusercontent.com/5555383/37341720-032c03ae-26f5-11e8-8dc2-5bec7e1f4aa9.png)
Thanks!

**Comment by kirigayakazushin** [comment]
You can only do it by modifying the source code.

https://github.com/kirigayakazushin/deepin-topbar/blob/master/frame/mainpanel.cpp#L164

remove this line. and reinstall.

**Comment by rafipriatna** [comment]
@kirigayakazushin   Thank you!, btw i can't install this packages after update my Arch. This topbar uninstalled autmatically then when i want to reinstall, error message appears. Like this 
[Makefile:45: sub-frame-make_first] Error 2

**Comment by kirigayakazushin** [comment]
The dbus interface of the library is updated. You can switch to the dev branch to continue.

**Comment by rafipriatna** [comment]
@kirigayakazushin I'm use the dev, like what you say : https://github.com/kirigayakazushin/deepin-topbar/tree/dev

But still i got a error

../../modules/notify/notifymodel.cpp: In constructor ‘dtb::notify::NotifyModel::NotifyModel(QObject*)’:
../../modules/notify/notifymodel.cpp:35:43: error: ‘RecordAdded’ is not a member of ‘org::freedesktop::Notifications {aka __Notifications}’
     connect(m_notifyDBus, &Notifications::RecordAdded, this, &NotifyModel::onNotifyAdded);
                                           ^~~~~~~~~~~
../../modules/notify/notifymodel.cpp:37:88: error: ‘org::freedesktop::Notifications {aka class __Notifications}’ has no member named ‘GetAllRecords’
     QDBusPendingCallWatcher *notifyWatcher = new QDBusPendingCallWatcher(m_notifyDBus->GetAllRecords(), this);
                                                                                        ^~~~~~~~~~~~~
make[1]: *** [Makefile:2014: notifymodel.o] Error 1
make[1]: Leaving directory '/home/rafi/Desktop/ea/Build/frame'
make: *** [Makefile:45: sub-frame-make_first] Error 2

**Comment by kirigayakazushin** [comment]
please update deepin-qt-dbus-factory to 1.0.1-1. and deepin-topbar updated to 0.4.0 for aur.
