### ISSUE TITLE
Fail to compile

### ISSUE THREAD

**Issue by Maxximo88** [kirigayakazushin/deepin-topbar#5]
I tried to compile from Github, I get this issue:

maxximo88@maxximo88-PC:~/deepin-topbar/build$ make
cd frame/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/maxximo88/deepin-topbar/frame/frame.pro -o Makefile ) && make -f Makefile 
make[1]: ingresso nella directory "/home/maxximo88/deepin-topbar/build/frame"
g++ -c -m64 -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DQT_MESSAGELOGCONTEXT -DQT_MESSAGELOGCONTEXT -DQT_NO_DEBUG -DQT_X11EXTRAS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I../../frame -I. -I../../interfaces -I../../widgets -isystem /usr/include/libdtk-1.0/DWidget -isystem /usr/include/libdtk-1.0/DBase -isystem /usr/include/libdtk-1.0/DUtil -isystem /usr/include/libdframeworkdbus-1.0 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o switchitem.o ../../widgets/switchitem.cpp
g++ -c -m64 -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DQT_MESSAGELOGCONTEXT -DQT_MESSAGELOGCONTEXT -DQT_NO_DEBUG -DQT_X11EXTRAS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I../../frame -I. -I../../interfaces -I../../widgets -isystem /usr/include/libdtk-1.0/DWidget -isystem /usr/include/libdtk-1.0/DBase -isystem /usr/include/libdtk-1.0/DUtil -isystem /usr/include/libdframeworkdbus-1.0 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o main.o ../../frame/main.cpp
g++ -c -m64 -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DQT_MESSAGELOGCONTEXT -DQT_MESSAGELOGCONTEXT -DQT_NO_DEBUG -DQT_X11EXTRAS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I../../frame -I. -I../../interfaces -I../../widgets -isystem /usr/include/libdtk-1.0/DWidget -isystem /usr/include/libdtk-1.0/DBase -isystem /usr/include/libdtk-1.0/DUtil -isystem /usr/include/libdframeworkdbus-1.0 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o mainframe.o ../../frame/mainframe.cpp
In file included from ../../frame/item/item.h:4:0,
                 from ../../frame/item/pluginsitem.h:5,
                 from ../../frame/controller/pluginscontroller.h:5,
                 from ../../frame/controller/pluginsitemcontroller.h:4,
                 from ../../frame/mainpanel.h:4,
                 from ../../frame/mainframe.cpp:2:
../../frame/utils/itempopupwindow.h:7:32: fatal error: DWindowManagerHelper: File o directory non esistente
 #include <DWindowManagerHelper>
                                ^
compilation terminated.
Makefile:494: set di istruzioni per l'obiettivo "mainframe.o" non riuscito
make[1]: *** [mainframe.o] Errore 1
make[1]: uscita dalla directory "/home/maxximo88/deepin-topbar/build/frame"
Makefile:43: set di istruzioni per l'obiettivo "sub-frame-make_first" non riuscito
make: *** [sub-frame-make_first] Errore 2

-----------
Maybe a Deb installation file could be useful!!

**Comment by renorram** [comment]
See #4

**Comment by kirigayakazushin** [comment]
@Maxximo88  https://blog.mkacg.com/2017/07/20/topbar-PPA/ please use it.

**Comment by Maxximo88** [comment]
Thank you so much. I'm "Maxximo88" on the italian Telegram Group of Deepin
:)

Massimo Antonio Carofano
<http://www.linkedin.com/in/massimocarofano>

2017-07-20 11:11 GMT+02:00 小竹 <notifications@github.com>:
