### ISSUE TITLE
安装后topbar原有dock中的这部分右键左键均失效

### ISSUE THREAD

**Issue by wallena3** [kirigayakazushin/deepin-topbar#55]
![image](https://user-images.githubusercontent.com/11361768/39346919-0de03198-4a23-11e8-9771-ca3c9f16844e.png)

**Comment by kirigayakazushin** [comment]
因为dock那边的托盘窗口已经失效了，暂时无法解决。

**Comment by kirigayakazushin** [comment]
我给dock加了点私货…

**Comment by wallena3** [comment]
这波操作可以,,,

**Comment by kirigayakazushin** [comment]
arch上已经可以工作了，deepin需要等15.6推送正式版更新。
