### ISSUE TITLE
where is the link of ppa?

### ISSUE THREAD

**Issue by chemel9** [kirigayakazushin/deepin-topbar#59]
HI please, update your blog, it is down ,
i need to install by ppa
https://blog.ilxz.me/2017/07/20/topbar-ppa/

**Comment by kirigayakazushin** [comment]
sorry, new link.
https://blog.ilxz.me/topbar-ppa/

**Comment by chemel9** [comment]
your blog is down 
, 404 Not Found
https://blog.ilxz.me/topbar-ppa/
